#Este es el archivo docker-compose.yml que define los servicios de la aplicacion VRISA: base de datos PostGIS, cache Redis, backend Django y frontend React. Infra es de infrastructura, XD.

version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: vrisa_db
    environment:
      POSTGRES_DB: vrisa
      POSTGRES_USER: vrisa_user
      POSTGRES_PASSWORD: vrisa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data #Ocho, aqui se guarda la data de la base de datos
    
    healthcheck: #Esto es un healthcheck para asegurarse de que la base de datos este lista antes de que el backend intente conectarse
      test: ["CMD-SHELL", "pg_isready -U vrisa_user -d vrisa"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7 #Redis es un sistema de almacenamiento en cache en memoria, yauda a mejorar el rendimiento de la aplicacion
    container_name: vrisa_redis
    ports:
      - "6379:6379"

  backend: #El servicio del backend, que corre Django
    build: ../backend
    container_name: vrisa_backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
      - /app/__pycache__
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure
    environment: #Aqui se definen las variables de entorno para la conexion a la base de datos
      - DB_HOST=db
      - DB_NAME=vrisa
      - DB_USER=vrisa_user
      - DB_PASSWORD=vrisa_pass
      - DB_PORT=5432

  frontend:
    build: ../frontend
    container_name: vrisa_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  postgres_data: #Volumen para persistir los datos de la base de datos Postgres
