version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: vrisa_db
    environment:
      POSTGRES_DB: vrisa
      POSTGRES_USER: vrisa_user
      POSTGRES_PASSWORD: vrisa_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vrisa_redis
    ports:
      - "6379:6379"

  backend:
    build: ../backend
    container_name: vrisa_backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../backend:/app
      - /app/__pycache__
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=vrisa
      - DB_USER=vrisa_user
      - DB_PASSWORD=vrisa_pass
      - DB_PORT=5432

  frontend:
    build: ../frontend
    container_name: vrisa_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
